### ISSUE TITLE
Milestone 1 feedback

### ISSUE THREAD

**Issue by eric-f** [UBC-MDS/DSCI_522_Pokemon_Legendariness_Classifier#29]
__Mechanics__
- [ ] Looks like the README is the same as the final report? Perhaps you can make the README as a more condensed version of the full report. Keep it short and sweet for this lab?
- [ ] Need add a housekeeping section to README on dependencies, how to run the data analysis, e.g. script order, expected inputs/outputs, etc.

__Quality__
- [ ] For the scripts, need to document at the top, the authors, time created and a description of what the script does. 
- [ ] You have done this for `2_pokemonEDA.R` but not the other scripts.
- [ ] Also, for each function, explain the arguments in addition to showing an usage example.

__Others__
- [ ] You closed my proposal feedback issue with no comments or discussions. Please do response to my feedback this time. 

__Report__
- [ ] Should have provide an brief overview of all the predictors in the introduction section. Maybe list them out with some brief summary statistics?
- [ ] How about changing the x-axis from count to proportion in Figure 3? Quite difficult to compare the distribution between Legendary and Non-Legendary group. Difficult to compare the proportion of Legendary/Non-Legendary by Type neither.
- [ ] I know I have been complaining about just dumping the default tree diagraph from Python in other groups but it would be nice to see your fitted tree somewhere, somehow...
- [ ] Also, you mentioned cross-validation but did not present any results. Would be nice to report your CV error rates by tree depth.
- [ ] A quick comment on kNN. Seems very challenging to define 'neighbourhood' or distance when some of the features are categorical...
- [ ] Is it possible to center-justify the figure lables and captions?

**Comment by RayceRossum** [comment]
Hi Eric, thanks for the feedback!

Some of it has been incorporated into Milestone 2 now. We'll look to address more in the future. 
Agreed about kNN, we'd have to drop the "Types", they don't seem to make any difference in the decision tree, although I'm not sure if that would affect the results of kNN

**Comment by jackattackyang** [comment]
Hey Eric,
We also listened to the feedback from other groups and made changes to balance out the data set. The issue for this has already been resolved. 

In summary:  
- optimal tree depth is now 8, previously 2
- a wider variety of features are generated 

This should be a much more accurate representation of the actual predictors. More details see updated report under "Update Milestone 2:"

Thanks and enjoy HK!
